apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopyfs-daemon
rules:
- apiGroups:
  - ""
  resources:
  - PersistentVolumeClaims
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopyfs-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopyfs-daemon
subjects:
- kind: ServiceAccount
  name: daemon
  namespace: kopyfs
